### ISSUE TITLE
otf, pxjahyper との不具合？

### ISSUE THREAD

**Issue by ryoya9826** [aminophen/plautopatch#15]
こんにちは．

冒頭で \RequirePackage{plautopatch} をした上で，otf パッケージと hyperref パッケージを単に読み込むとエラーになるようです．どうやらplauthpatch を読まずに \usepackage{pxjahyper} とするとエラーは出ず，
\AtBeginDocument{ 
     \RequirePackage{pxjahyper}
}
とするとエラーになりますので，どうやらplautopatch において，\AtBeginDocument{\platpc@patch@after{hyperref}{pxjahyper}} としていることに起因しているのではないかと思われますが，見当違いでしたら申し訳ありません．

エラーとなるソース例とlog を添付しておきます．よろしくお願いいたします．
[document.zip](https://github.com/aminophen/plautopatch/files/6021099/document.zip)

**Comment by h-kitagawa** [comment]
とりあえず走らせただけでほとんど調べていませんが，pLaTeX （用に uplatex オプションを外したり）ではエラーが出ないことと，エラーの内容が
```
! Undefined control sequence.
l.575   \ifpxhy
               @hy@unicode PU\else PD1\fi
```
なので，\makeatletter/\makeatother まわりと推測しています．

**Comment by h-kitagawa** [comment]
`\pxhy@dispatch@otfcid` の内部で `\makeatother` が実行されることが原因のようです．
最善の方法かはわかりませんが，とりあえず
``` diff
--- /opt/texlive/2020/texmf-dist/tex/platex/pxjahyper/pxjahyper.sty     2021-02-14 07:17:47.000000000 +0900
+++ /tmp/pxjahyper.sty  2021-02-23 09:19:38.802554343 +0900
@@ -540,7 +540,7 @@
   }%
   \ifpxhy@otfmacros
     \ifx\ajSnowman\@undefined\else % ajmacros is loaded
-      \makeatletter
+      \edef\pxhy@cattemp{\noexpand\catcode`\noexpand\@=\the\catcode`\@ }\makeatletter
       \InputIfFileExists{pxjahyper-ajm.def}{%
         \PackageInfo\pxhy@pkgname
          {Loaded 'pxjahyper-ajm.def'\@gobble}%
@@ -548,7 +548,7 @@
         \PackageWarning\pxhy@pkgname
          {File 'pxjahyper-ajm.def' not found\@gobble}%
       }%
-      \makeatother
+      \pxhy@cattemp
     \fi
   \fi
 }
```
のようにするとどうでしょうか？

**Comment by aminophen** [comment]
pxjahyper の修正および現在の plautopatch では起きないはずなので閉じます。
