### ISSUE TITLE
plext と arydshln の衝突

### ISSUE THREAD

**Issue by tattsan** [aminophen/plautopatch#5]
かなり前ですが、次のような話がありました。
[https://oku.edu.mie-u.ac.jp/~okumura/texfaq/qa/12259.html](https://oku.edu.mie-u.ac.jp/~okumura/texfaq/qa/12259.html)

**Comment by aminophen** [comment]
私も plext+arydshln の衝突は把握していたので TODO リストには入っておりましたが，過去に forum で既出だったのですね。情報提供ありがとうございます。

**Comment by aminophen** [comment]
TeX QA に掲示してあるコードは確かに動くのですが，

- arydshln には「array，longtable，colortab，colortbl 各々への共存対策」が入っているため，それらを壊さないかどうか精査が必要。
- その前段階として，そもそも「plext + colortbl がエラーにならないようにする」が必須。
    - ここで，colortbl にも「delarray，longtable への共存対策」が入っていることに注意。
- ところが， arydshln と delarray は非互換 https://latex.org/forum/viewtopic.php?t=1523

というわけで，なかなか時間が取れそうにありません。ゆっくり考えます。

**Comment by tattsan** [comment]
全部に対応しようとすると大変ですね。

このように、複数パッケージの併用対策が入り乱れている事は
LaTeXの問題点の1つですね。

**Comment by aminophen** [comment]
> plext + colortbl がエラーにならないようにする

plextcolortbl.sty を追加し，plautopatch.sty に登録しました。

> plext + ardyshln がエラーにならないようにする

plextarydshln.sty を追加しました。まだ他のパッケージとの共存は確かめていないので plautopatch.sty には登録していませんが，追って改善していきます。

**Comment by aminophen** [comment]
> arydshln と delarray は非互換

この問題は，

(1) `%% Initialization` 直後のコード

```` tex
\let\adl@array\@array
\def\@array{\adl@everyvbox\everyvbox
        \everyvbox{\adl@arrayinit \the\adl@everyvbox \everyvbox\adl@everyvbox}%
        \ifadl@inactive \adl@inactivate \else \adl@activate \fi
        \let\adl@noalign\noalign
        \adl@array}
\let\@@array\@array
````

を以下のように変更し，

```` tex
% prepare temporary definition
\def\adl@temp@array{\adl@everyvbox\everyvbox
        \everyvbox{\adl@arrayinit \the\adl@everyvbox \everyvbox\adl@everyvbox}%
        \ifadl@inactive \adl@inactivate \else \adl@activate \fi
        \let\adl@noalign\noalign
        \adl@array}
\ifx\@@array\undefined
  % commit to \@array of LaTeX original
  \let\adl@array\@array
  \let\@array\adl@temp@array
\else
  % commit to \@array of array.sty or delarray.sty
  \let\adl@array\@@array
  \let\@@array\adl@temp@array
\fi
% no longer needed
\let\adl@temp@array\undefined
````

(2) もう一箇所 `%% End of Environment` 直後のコード

```` tex
\def\endarray{\adl@endarray \egroup \adl@arrayrestore \egroup}
````

を以下のように変更し，

```` tex
\ifadl@usingarypkg
\def\endarray{\adl@endarray \egroup \adl@arrayrestore \egroup \@arrayright}
\else
\def\endarray{\adl@endarray \egroup \adl@arrayrestore \egroup}
\fi
````

(3) あともう一箇所，colortbl 対策を施している部分も

```` tex
\def\endarray{\adl@endarray \egroup \adl@arrayrestore \CT@end \egroup}
````

を

```` tex
\def\endarray{\adl@endarray \egroup \adl@arrayrestore \CT@end \egroup \@arrayright}
````

に変更すれば良いようです。中島先生に連絡してみようと思います。

**Comment by aminophen** [comment]
あともう一箇所，colortbl 対策を施している部分も

```` tex
\def\endarray{\adl@endarray \egroup \adl@arrayrestore \CT@end \egroup}
````

を

```` tex
\def\endarray{\adl@endarray \egroup \adl@arrayrestore \CT@end \egroup \@arrayright}
````

にしないといけませんね。

**Comment by tattsan** [comment]
arydshln.sty 本体を修正して頂けるのであれば、
いずれはplext対策も採用して頂けそうですね。

**Comment by aminophen** [comment]
> arydshln.sty 本体を修正して頂けるのであれば、いずれはplext対策も採用して頂けそうですね。

私はむしろ採用していただかない方がいいのでは，と思っています。というのも，

- arydshln は「array が読み込まれていれば array 用のコードが動作し，そうでなければ普通のコードが動作する」という仕様である。
- 仮に plext 対策を入れてもらうことにすると，元々 plext と array が衝突していることへの対策もお願いすることになる。（colortbl，delarray も同様。）

今の arydshln は「plext をまったく考慮しない」という単純明快な状態です。だから，

- 私が plextarydshln というパッケージを開発する。
- arydshln のマニュアルに「plext を使うときは plextarydshln を使ってね」と書いてもらう。

くらいが無難ではないかと思います。

**Comment by aminophen** [comment]
arydshln と delarray の衝突について，中島先生からお返事をいただき，より簡潔な修正コードをご提案いただきました。ひとまずそちらはなんとかなりそうです。

**Comment by aminophen** [comment]
> arydshln のマニュアルに「plext を使うときは plextarydshln を使ってね」と書いてもらう。

中島先生に打診してみたところ，これについても了承いただけました。というわけで，私の方で plextarydshln の開発を継続していきます。

**Comment by aminophen** [comment]
arydshln v1.74 が今日 CTAN に出ました。delarray への対応，マニュアルでの plextarydshln への言及がなされています。あとは私の plextarydshln ですが， f2c413f で array / delarray / colortbl への対応が完了しています（v1.74 ベース）。かなり動作安定してきたので，plextarydshln も plautopatch での自動実行に含めることにします。

**Comment by aminophen** [comment]
plautopatch 2018-10-02 を出したので，ひとまずここは完了とします。

<img width="1280" alt="20181002-tabarray" src="https://user-images.githubusercontent.com/9957466/46352710-67e09b80-c695-11e8-9762-2f19879c97c4.png">

図にまとめました。
